### ISSUE TITLE
Improve About page, especially mention Windows

### ISSUE THREAD

**Issue by cdeil** [cdeil/healpix#24]
I see that 
http://healpix.readthedocs.io/en/latest/about.html
still exists, and it's referenced from the front page:
http://healpix.readthedocs.io/en/latest/index.html#about-this-package

Possibly that about page could be removed (moving essential info on docs front page), or updated.

Specifically, I think one important point to make is that this package fully supports Windows.
My understanding is that the HEALPix C++ library and healpy aren't fully supported on Windows, or don't work at all on Windows. E.g. healpy doesn't seem to have a Windows package on conda-forge:
https://github.com/conda-forge/healpy-feedstock#current-build-status

Pretty much all of the packages using Astropy and healpy (reproject, hips, gammapy, ... probably more ... ) would like to fully support Windows. So apart from the license and installation issues with healpy, Windows support is a huge selling point that everyone will understand why a new package even with a healpy-compatible API is needed.

**Comment by astrofrog** [comment]
@cdeil - I've tidied up the about page, which now also mentions windows. I also mentioned windows (and other OSes) on the installation page. I don't want to move everything in about to the front page otherwise it might be a bit overwhelming. Does the current page look good? If so, can you close this?

**Comment by cdeil** [comment]
I'm closing this issue. We still have #10 and #47 open and I think the remaining discussion is mostly about names, so this extra issue doesn't help.
