### ISSUE TITLE
BUG: incorrect results for large values of nside

### ISSUE THREAD

**Issue by astrofrog** [cdeil/healpix#28]
At the moment, the tests ``test_ang2pix`` and ``test_ang2pix`` are not run for values of ``nside`` greater than 2**22, because the results then start to diverge between this package and healpy. I think this is because of issues with 32- vs 64-bit ints in the C code. One solution might be to simply update the C code to use int64_t throughout rather than mix int and int64_t as we do currently. Lower priority is that ``test_nest2ring`` and ``test_ring2nest`` fail for ``nside=2**29``, probably for similar reasons to those above.

If anyone is interested in investigating, please feel free to take a look - you can reproduce the failures by setting the ``integers(...)`` calls in ``test_healpy.py`` to ``integers(0, 29)``.

**Comment by astrofrog** [comment]
Just to be clear, nside=2**22 corresponds to 0.05" resolution, so while this should be fixed, the package is still usable as-is for larger resolutions.

**Comment by cdeil** [comment]
> One solution might be to simply update the C code to use int64_t throughout rather than mix int and int64_t as we do currently.

Any reason not to do this? Correctness is more important than performance (if it's a performance concern) no? Should it be uint64 or int64?

**Comment by astrofrog** [comment]
Mainly performance, though I think it might make sense to first try 64-bit ints and see if that causes any issues. It should be ``int64_t`` (which is already used for some variables).

**Comment by astrofrog** [comment]
@cdeil - I've identified the culprit integers, so I'll fix that for now, but in future we could indeed convert all ints to 64-bit if we want anyway (but I'll defer that for now). PR forthcoming.

**Comment by astrofrog** [comment]
There are still issues, so I'm tempted to actually do this (change all ints to 64-bit)

**Comment by astrofrog** [comment]
I'm going to close this and open another clean issue that is more up-to-date
