### ISSUE TITLE
Doctests fail locally

### ISSUE THREAD

**Issue by cdeil** [cdeil/healpix#32]
For me locally the doctests for this package fail like this:
https://gist.github.com/cdeil/027f1069bc11605c3f8ce47e4cd26a54#file-gistfile1-txt-L366
```
ImportError while importing test module '/private/var/folders/sb/4qv5j4m90pz1rw7m70rj1b1r0000gn/T/healpix-test-5bbl3j6d/docs/about.rst'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
ModuleNotFoundError: No module named 'about'
```
This issue is not seen on travis-ci: https://travis-ci.org/cdeil/healpix/jobs/279497877#L950

@astrofrog - Can you reproduce? Any thoughts what's wrong / how to fix it? (I tried `git clean -fdx`).

**Comment by astrofrog** [comment]
@cdeil - yes, this is a bug with Astropy that I'm going to open a PR for

**Comment by astrofrog** [comment]
The fix is in https://github.com/astropy/astropy/pull/6605/files

**Comment by astrofrog** [comment]
This is fixed in Astropy core. I don't think there's any point in leaving this issue open.
